import * as categories from '../constants/categories';

export default {
  [categories.WebTechnologies]: [
    'Що таке прогресивний рендерінг?',
    'Що таке прогресивний SSR?',
    'SSR (Server-Side Rendering) і CSR (Client-Side Rendering), переваги і недоліки?',
    'Що таке Progressive Web Application (PWA)?',
    'Що таке кросбраузерність?',
    'Що таке OSI модель?',
    'Що таке потік документа?',
    'Різниця мід adaptive і responsive дизайнами?',
    'Різниця між Progressive Enhancement і Graceful Degradation?',
    'Що таке Веб-компоненти і які технології в них використовуються?',
    'Особливості розробки мультимовних сайтів?',
    'Що таке REST?',
    'Що таке REST і RESTful api?',
    'Принципи REST-архітектури?',
    'Що таке модель зрілості Річардсона?',
    'Основні рівні моделі зрілості Річардсона?',
    'Критичні етапи рендерінга?',
    'Різниця між layout, painting і compositing?',
    'Що таке Flash Of Unstyled Content (FOUC)? , як його уникнути?',
    'Що таке History API в браузері?',
    'Що таке web storage?',
    'Різниця між cookie, sessionStorage і localStorage?',
    'Способи скорочення часу завантаження веб сторінки?',
    'Що таке Core Web Vitals, які основні метрики туди входять?',
    'Розкжіть про метрики Core Web Vitals?',
    'Різниця між preload, prefetch, preconnect і prerender?',
    'Для чего нужен паттерн PRPL?',
    'Що таке HTTP?',
    'З чого складається HTTP-запит?',
    'Які методи може мати HTTP-запит?',
    'Що таке HTTP cookie, для чого вони використовуються?',
    'Різниця між HTTP і HTTPS?',
    'Різниця між HTTP/1 і HTTP/2?',
    'Як працює мультипрлексування в HTTP/2?',
    'Що таке Triple handshake?',
    'Різниця між PUT- і POST-запитами?',
    'Різниця між TCP і UDP?',
    'Що таке WebSocket, в чому принцип його роботи?',
    'Різниця між Long-Polling, Websockets і Server-Sent Events?',
    'Як працює JSONP?',
    'Що таке IndexedDB в браузері, переваги IndexedDB?',
    'Що таке Service Workers?',
    'Що таке Web Workers?',
    'Що таке Web Worklet?',
    'Механізм установки сеансу між кліентом і сервером?',
    'Що таке API?',
    'Що таке CDN?',
    'Що таке IP-адрес?',
    'Різниця між host і domain?',
    'Різниця між URI і URL?',
    'Чому важливо очищати кеш, як це можна зробити?',
  ],
};
